spring:
  application:
    name: CONFIG-SEVER
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Vamsi-Yalla/cloudConfigservices.git

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
server:
  port: 8002
  
