spring:
  application:
    name: GatewayExample
  cloud:
    gateway:
      mvc:
        routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
          - Path= /order/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
          - Path= /payment/**
    config:
      uri: 
       - http://localhost:8002 
   
  config:
    import: "optional:configserver:"
   
server:
  port: 8001   
   
    
   
   